### Variables 
@url = http://localhost:3000
@id = 663ab8a94a6e02ff10685bfe

### Get all menu items

#GET {{url}}/api/menu

## Add a new item
#POST {{url}}/api/menu
#Content-Type: application/json

# {
#     "name": "Test",      
#     "description": "This will be deleted! ",
#     "price": {
#         "$numberDecimal": "3.00"
#     }
# }

## Get menu item by id
#GET {{url}}/api/menu/{{id}}

## Update menu item by id
PUT {{url}}/api/menu/{{id}}
Content-Type: application/json

{
    "name": "Test Update",      
    "description": "This will be deleted! ",
    "price": {
        "$numberDecimal": "5.00"
    }
}

### Add new Event 

POST {{url}}/events
Content-Type: application/json
{
    "name":"AAPI Celebration ",
    "location":"1065 Lombardi Ave, Green Bay, WI 54304 ",
    "dates":"May 15 2024 ",
    " hours": "5:30pm - 8pm "
}

### Update Event List
PUT {{url}}/events/{{id}}

{
    "name":"AAPI Celebration ",
    "location":"1065 Lombardi Ave, Green Bay, WI 54304 ",
    "dates":"May 20 2024 ",
    " hours": "5:30pm - 8pm "
}

### DELETE Event 

DELETE {{url}}/events/{{id}}

{
    "name":" AAPI Celebration ",
    "location":" 1065 Lombardi Ave, Green Bay, WI 54304 ",
    "dates":" May 20 2024  ",
    " hours": " 5:30pm - 8pm "
}


